# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "chill"
  high_level_summary: true

  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  suggested_labels: false
  suggested_reviewers: false
  poem: false
  
  # Auto review settings
  auto_review:
    enabled: true
    drafts: false
    
    # Ignore PRs with these keywords in title
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "ci(changesets)"
      - "chore(deps)"
      - "docs:"
      - "[skip review]"
    
    # Monitored base branches
    base_branches:
      - "main"
      - "dev"
      - "fix/.*"
      - "chore/.*"
      - "feat/.*"
      - "refactor/.*"
      - "test/.*"
