coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      patch:
        target: 100%
        threshold: 0%
        branches:
          - dev
