import { Input, Flex } from '@nex-ui/react'

export default function App() {
  return (
    <Flex gap='5' wrap='wrap'>
      <Input
        label='Color'
        labelPlacement='float-inside'
        variant='faded'
        size='lg'
        color='blue'
        defaultValue='blue'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='cyan'
        defaultValue='cyan'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='gray'
        defaultValue='gray'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='green'
        defaultValue='green'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='orange'
        defaultValue='orange'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='pink'
        defaultValue='pink'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='purple'
        defaultValue='purple'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='yellow'
        defaultValue='yellow'
      />
      <Input
        label='Color'
        size='lg'
        labelPlacement='float-inside'
        variant='faded'
        color='red'
        defaultValue='red'
      />
    </Flex>
  )
}
