export default {
  '#': {
    type: 'separator',
    title: 'THEME',
  },
  theming: 'Theming',
  'dark-mode': 'Dark Mode',
  scales: 'Scales',
  tokens: 'Tokens',
  'semantic-tokens': 'Semantic Tokens',
  components: 'Components',
  aliases: 'Aliases',
  breakpoints: 'Breakpoints',
  selectors: 'Selectors',
  '##': {
    type: 'separator',
    title: 'DESIGN TOKENS',
  },
  colors: 'Colors',
  sizes: 'Sizes',
  spaces: 'Spaces',
  radii: 'Radii',
  shadows: 'Shadows',
  borders: 'Borders',
  'border-widths': 'BorderWidths',
  transitions: 'Transitions',
  typography: 'Typography',
  'z-indexes': 'Z-Indexes',
}
