import { defineConfig } from '@nex-ui/system'

export const scales = defineConfig.scales({
  color: 'colors',
  borderColor: 'colors',
  backgroundColor: 'colors',
  borderBottomColor: 'colors',
  borderTopColor: 'colors',
  borderLeftColor: 'colors',
  borderRightColor: 'colors',
  fill: 'colors',
  stroke: 'colors',

  width: 'sizes',
  minWidth: 'sizes',
  maxWidth: 'sizes',
  height: 'sizes',
  minHeight: 'sizes',
  maxHeight: 'sizes',

  fontWeight: 'fontWeights',
  lineHeight: 'lineHeights',
  fontFamily: 'fontFamilies',
  fontSize: 'fontSizes',

  padding: 'spaces',
  paddingTop: 'spaces',
  paddingBottom: 'spaces',
  paddingLeft: 'spaces',
  paddingRight: 'spaces',
  marginRight: 'spaces',
  marginTop: 'spaces',
  marginLeft: 'spaces',
  marginBottom: 'spaces',
  margin: 'spaces',
  top: 'spaces',
  left: 'spaces',
  right: 'spaces',
  bottom: 'spaces',
  gap: 'spaces',
  rowGap: 'spaces',
  columnGap: 'spaces',
  gridGap: 'spaces',
  gridColumnGap: 'spaces',
  gridRowGap: 'spaces',
  outlineOffset: 'spaces',

  borderRadius: 'radii',
  borderTopRightRadius: 'radii',
  borderTopLeftRadius: 'radii',
  borderBottomRightRadius: 'radii',
  borderBottomLeftRadius: 'radii',

  borderTopWidth: 'borderWidths',
  borderBottomWidth: 'borderWidths',
  borderLeftWidth: 'borderWidths',
  borderRightWidth: 'borderWidths',
  borderWidth: 'borderWidths',

  border: 'borders',
  borderTop: 'borders',
  borderBottom: 'borders',
  borderRight: 'borders',
  borderLeft: 'borders',
  outline: 'borders',

  boxShadow: 'shadows',

  transition: 'transitions',

  zIndex: 'zIndexes',
})
