export default {
  accordion: 'Accordion',
  alert: 'Alert',
  avatar: 'Avatar',
  badge: 'Badge',
  button: 'Button',
  card: 'Card',
  checkbox: 'Checkbox',
  dialog: 'Dialog',
  divider: 'Divider',
  drawer: 'Drawer',
  flex: 'Flex',
  input: 'Input',
  popover: 'Popover',
  radioGroup: 'RadioGroup',
  switch: 'Switch',
  tooltip: 'Tooltip',
}
