import { NexUIProvider, InitColorSchemeScript } from '@nex-ui/react'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by nex ui cli',
}

const colorScheme = { colorSchemeSelector: 'class' }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <InitColorSchemeScript colorSchemeSelector='class' />
        <NexUIProvider colorScheme={colorScheme}>{children}</NexUIProvider>
      </body>
    </html>
  )
}
